// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function DefaultFolder() {
  return window['go']['main']['App']['DefaultFolder']();
}

export function Describe(arg1) {
  return window['go']['main']['App']['Describe'](arg1);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickDestination() {
  return window['go']['main']['App']['PickDestination']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickFolderToSend() {
  return window['go']['main']['App']['PickFolderToSend']();
}

export function Receive(arg1, arg2) {
  return window['go']['main']['App']['Receive'](arg1, arg2);
}

export function Send(arg1, arg2) {
  return window['go']['main']['App']['Send'](arg1, arg2);
}
