// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<Record<string, string>>;

export function Cancel():Promise<void>;

export function CheckForUpdates(arg1:boolean):Promise<main.UpdateStatus>;

export function DefaultFolder():Promise<string>;

export function Describe(arg1:Array<string>):Promise<Array<main.FileEntry>>;

export function GetProgress():Promise<main.Progress>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickDestination():Promise<string>;

export function PickFiles():Promise<Array<main.FileEntry>>;

export function PickFolderToSend():Promise<Array<main.FileEntry>>;

export function Receive(arg1:string,arg2:string):Promise<void>;

export function Send(arg1:Array<string>,arg2:string):Promise<string>;
